### ISSUE TITLE
Licence for port and driver code

### ISSUE THREAD

**Issue by antiprism** [wuhanstudio/u8g2-arm-linux#2] opened 2019-09-27 12:30 UTC
Hi

Great work on the port!

I would like to use code from the port and I was wondering what the licence details are for the files in the _port_ and _drivers_ subdirectories?

I plan to use the port for the [mpd_oled](https://github.com/antiprism/mpd_oled) project, but rather than include the code inside the projject I thought it would be better if it was packaged as a separate easy-to-install library. I have uploaded a C-only preview here (using the latest u8g2 code) : https://github.com/antiprism/libu8g2arm_test

The next step is to generate a compatible C++ interface.

Adrian.

**Comment by wuhanstudio** [comment] 2019-09-27 13:13
Hi, Adrian

I'm really happy that my work on u8g2-arm-linux can be used in your project. The files under 'port' and 'drivers' are licensed under MIT, so you can just take it with no problem. But I'd appreciate it if you can add a reference somewhere.

```
Author: Wu Han
Home : http://wuhanstudio.cc
Email: wuhanstudio@hust.edu.cn
```

As for this C-only port, push buttons for menu selection is not implemented. In addition, software i2c and softwate SPI can be defined in linux device tree, thus not implemented either. As for 8080 mode, I haven't found a way fast enough to deal with it in linux user space. I hope it helps to tell you some work that I haven't done yet.

Acutally, as for C++ interface, I've implemented one [here](https://github.com/wuhanstudio/rt-u8g2) for [RT-Thread](https://github.com/rt-thread/rt-thread), a burgeoning RTOS in China. All of sw i2c, sw SPI, hw i2c, hw SPI, 8080, push buttons have been implemented in this port. Though the README is written in Chinese, the source code isn't ;) I hope you may find it helpful.

Wu Han
吴晗

**Comment by antiprism** [comment] 2019-09-27 18:24
Hi Wu Han

Thanks! I will add the MIT licence to the files with your details, and  also include your details in the project documentation.

Thanks also for the extra information. I will have a look at the specific changes in the u8g2 C++ interface for RT-Thread. Ideally, I will generate the C++ interface from the u8g2 source. I also need a function that will set up the display based on string values of name/resolution/interface/etc (from command line parameters of configuration file vaues). I can probably generate both with a modified version of codebuild.c (from u8g2).

A quick question regarding the interface support, if I keep the current u8g2 class naimg then the _SW and _HW classes will both use the hw driver, is that right, and there is no driver for the _8080 setup and so there is no point in including these classes?

Adrian.

**Comment by wuhanstudio** [comment] 2019-09-28 02:31
Actually, the _SW classes will just not work since both sw driver and hw driver are wrapped in _HW classes. As for now, you can keep all _HW classes and they will work, while both _SW and _8080 setup won't.

Once I've found a way to deal with GPIOs fast enough, both _SW and _8080 will work. Turns out it has been achieved in both WiringPi and SwiftyGPIO.

https://github.com/uraimo/SwiftyGPIO
https://electronicayciencia.github.io/wPi_soft_i2c/

I'll try to implement _SW and _8080 next week.

**Comment by antiprism** [comment] 2019-09-28 09:14
Thanks. Just having the hardware drivers available is going to be a great improvement on the library I am currently using.

**Comment by wuhanstudio** [comment] 2019-10-01 01:28
> Thanks. Just having the hardware drivers available is going to be a great improvement on the library I am currently using.

Well, I've just added SW I2C, SW SPI, and 8080 mode support, though it should be much slower.

Now all of SW/HW I2C, SW/HW SPI, and 8080 mode are supported.

**Comment by antiprism** [comment] 2019-10-01 18:04
Thanks (quick work!). I'll generate the C++ header to include the devices supported by your new drivers.

**Comment by antiprism** [comment] 2019-10-07 14:47
I have added in the generation of the C++ classes, and updated to your latest code

   https://github.com/antiprism/libu8g2arm_test

These are some notes

LICENCES

The setup script prepends the MIT license to your code (I also added your details to a credit section in the README).

There may be a licensing issue with U8g2 library binaries. The binary will be built from font code that is licensed with the GPL and also font code licensed for non-commercial use. My understanding is that these licenses are imcompatible and so the binary cannot be distributed. I will ask the U8g2 project about this, and probably regenerate the fonts source file to exclude the non-commercial use fonts.

C++ SETUP CLASSES

The C++ classes are generated with setup/codebuild/codebuild_cpp.c (built and called from setup_src.sh). I have included all the classes for: SW SPI, HW SPI, 3wire SW SPI, 8080, SW I2C, HW I2C

The U8G2 class was derived from the Print class, which you include a version of with rt-u8g2, but I have removed this. (The Adafruit OLED library I am using also derived the controller class from
Print, and I removed it there too).

BUILD REPORT

I usually build with warnings -W -Wall, here are the warning messages I get when building the library (port/U8g2lib.* has been renamed to port/u8g2arm.*)

libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -W -Wall -g -O2 -MT port/u8g2arm.lo -MD -MP -MF port/.deps/u8g2arm.Tpo -c port/u8g2arm.c  -fPIC -DPIC -o port/.libs/u8g2arm.o
port/u8g2arm.c: In function ‘u8x8_arm_linux_gpio_and_delay’:
port/u8g2arm.c:26:89: warning: unused parameter ‘arg_ptr’ [-Wunused-parameter]
 linux_gpio_and_delay(u8x8_t *u8x8, uint8_t msg, uint8_t arg_int, void *arg_ptr)
                                                                  ~~~~~~^~~~~~~

port/u8g2arm.c: In function ‘u8x8_byte_arm_linux_hw_spi’:
port/u8g2arm.c:332:25: warning: statement with no effect [-Wunused-value]
                 case 0: internal_spi_mode; break;
                         ^~~~~~~~~~~~~~~~~
port/u8g2arm.c:294:20: warning: variable ‘buf_idx’ set but not used [-Wunused-but-set-variable]
     static uint8_t buf_idx, internal_spi_mode;
                    ^~~~~~~

libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -W -Wall -g -O2 -MT drivers/gpio.lo -MD -MP -MF drivers/.deps/gpio.Tpo -c drivers/gpio.c  -fPIC -DPIC -o drivers/.libs/gpio.o
drivers/gpio.c: In function ‘gpioToPin’:
drivers/gpio.c:89:16: warning: comparison of integer expressions of different signedness: ‘int’ and ‘unsigned int’ [-Wsign-compare]
     for(i=0; i < (unsigned)strlen(gpio); i++)
                ^

And when building against the library

g++ -W -Wall -std=c++11 -o cpp_ex01 -I/home/pi/proj/inst/include/   cpp_ex01.cpp /home/pi/proj/inst/lib/libu8g2arm.a
In file included from cpp_ex01.cpp:1:
/home/pi/proj/inst/include/libu8g2arm/u8g2arm.h:40:12: warning: ‘spi_device’ defined but not used [-Wunused-variable]
 static int spi_device;
            ^~~~~~~~~~
/home/pi/proj/inst/include/libu8g2arm/u8g2arm.h:37:12: warning: ‘i2c_device’ defined but not used [-Wunused-variable]
 static int i2c_device;
            ^~~~~~~~~~

I added extern "C" {} to port/U8g2lib.h (port/u8g2arm.h) to make it easier to use the library with C++.

**Comment by wuhanstudio** [comment] 2019-10-09 03:05
> -Wunused-paramete

According to **olikraus**, U8g2 code is licensed under the two-clause BSD license.

* Redistributions in binary form must reproduce the above copyright notice, this 
  list of conditions and the following disclaimer in the documentation and/or other 
  materials provided with the distribution.

While the fonts are licensed under different licenses. Indeed, it may be better to exclude the non-commercial use fonts. On my raspi zero, with all the fonts, the generated library **libu8g2armcsrc.a** and **libu8g2arm.so.0.0.0** take up 12-14 MB which a little heavy.

As for the warnings, all unused parameters are used in **switch case**, so I think these warnings can be ignored.  And the **-Wsign-compare** warning has been fixed.

By the way, I've just added two more TODOs into README.

**Comment by antiprism** [comment] 2019-10-09 07:44
The only problem with licensing comes from the font code. Any license that restricts to non-commercial use presumably implies that the library binary cannot be sold, while if it also includes GPL code then it is a condition that this restriction can't be placed on the library binary when distributed

   https://www.gnu.org/licenses/gpl-faq.html#NoMilitary

I'll see if I can have the package generation script strip out the non-commercial fonts (and maybe put them in their own library for people who have code that depends on them).

Regarding the warnings, it was mostly in case you wanted a build without warnings (all the u8g2 source builds without warnings, and so they are the only warnings when building the library). However, I wondered about the use of static variables in the header in the code referenced in the last warnings

   https://stackoverflow.com/questions/3837490/initializing-a-static-variable-in-header

Great that you are still improving the port!

**Comment by wuhanstudio** [comment] 2019-10-09 08:03
> The only problem with licensing comes from the font code. Any license that restricts to non-commercial use presumably implies that the library binary cannot be sold, while if it also includes GPL code then it is a condition that this restriction can't be placed on the library binary when distributed
> 
> https://www.gnu.org/licenses/gpl-faq.html#NoMilitary
> 
> I'll see if I can have the package generation script strip out the non-commercial fonts (and maybe put them in their own library for people who have code that depends on them).
> 
> Regarding the warnings, it was mostly in case you wanted a build without warnings (all the u8g2 source builds without warnings, and so they are the only warnings when building the library). However, I wondered about the use of static variables in the header in the code referenced in the last warnings
> 
> https://stackoverflow.com/questions/3837490/initializing-a-static-variable-in-header
> 
> Great that you are still improving the port!

Thanks for pointing it out which is indeed a bad practice putting static variables in the header file, and I've just fixed it.

**Comment by wuhanstudio** [comment] 2019-10-09 08:32
I've switched on the option **-W -Wall** in my Makefile, and will try to fix those warnings.

While this one may still remain there since **arg_ptr** is indeed not used in **u8x8_arm_linux_gpio_and_delay** but required for function declaration to match with **u8g2_setup** such as **u8g2_Setup_ssd1306_128x64_noname_f**.

```
gcc -I ../../drivers -I ../../u8g2src -I ../../port -W -Wall   -c -o ../../port/U8g2lib.o ../../port/U8g2lib.c ../../port/U8g2lib.c: In function ‘u8x8_arm_linux_gpio_and_delay’: 
../../port/U8g2lib.c:9:89: warning: unused parameter ‘arg_ptr’ [-Wunused-parameter]
uint8_t u8x8_arm_linux_gpio_and_delay(u8x8_t *u8x8, uint8_t msg, uint8_t arg_int, void *arg_ptr) 
```

I think it's OK to just leave it as it is, or if you have any suggestion about this warning, I'll try to fix it.

Thanks for pointing out all those warnings.

**Comment by antiprism** [comment] 2019-10-09 09:34
I normally use C++, where you can just comment out the parameter name, but this doesn't work in C. Instead, it seems like the usual way is to reference the parameter in the function like this
```
(void) arg_ptr; /* suppress unused parameter warning */
```
https://stackoverflow.com/questions/4851075/universally-compiler-independent-way-of-implementing-an-unused-macro-in-c-c

**Comment by wuhanstudio** [comment] 2019-10-10 01:42
> I normally use C++, where you can just comment out the parameter name, but this doesn't work in C. Instead, it seems like the usual way is to reference the parameter in the function like this
> 
> ```
> (void) arg_ptr; /* suppress unused parameter warning */
> ```
> 
> https://stackoverflow.com/questions/4851075/universally-compiler-independent-way-of-implementing-an-unused-macro-in-c-c

Thanks, all the warnings have been fixed now.

Function reloading is not supported in C, so it seems one way to suppress the warning is to reference the parameter as you suggested, though it does nothing. For SoCs that are capable of running arm linux, I think it is fine to add several "NULL" instructions to suppress the warning.

**Comment by antiprism** [comment] 2021-06-26 15:37
Hi Wu Han

It has been a while! I have been looking at the libu8g2arm project again, and pushed an updated version

   https://github.com/antiprism/libu8g2arm

Main changes

* the fonts are now separated by licence type, allowing distributable binaries of the library (and programs that link to it) to be built
* there are functions for setting the I2C bus, and SPI bus/cs when using the hardware drivers
* there is a simple C++ initialisation class for specifying the controller at runtime

I have modified mpd_oled to use this library, and it is working well

![mpd_oled_u8g2_01](https://user-images.githubusercontent.com/2940060/123517861-a5867d80-d6a3-11eb-9057-41e8923806c5.jpg)

The controller is specified on the command line, and in this case the command was
```
./mpd_oled -o SH1106,128X64,I2C
```

Adrian.

**Comment by wuhanstudio** [comment] 2021-06-26 16:50
Hi, Adrian,

This looks quite interesting. I just tried this out on my raspi.

Perhaps you can consider adding your project to the u8g2 wiki, so that more people will know this great library.

https://github.com/olikraus/u8g2/wiki/Porting-to-new-MCU-platform#arm-linux

Han

**Comment by antiprism** [comment] 2021-06-27 06:27
Hi Han

That is a good idea! I have added a note to the wiki

   https://github.com/olikraus/u8g2/wiki/Porting-to-new-MCU-platform#raspberry-pi-library-package

Adrian.

**Closed as completed** 2023-09-22 09:35 UTC
